### ISSUE TITLE
Fails to run with "import cPickle" failed Error.

### ISSUE THREAD

**Issue by bhishanpdl** [deanishe/zothero#17]
My `/usr/bin/python` is aliased to `~/Library/Enthought/Canopy/edm/envs/User/bin/python`
```
~/Library/Enthought/Canopy/edm/envs/User/bin/python --version
Python 3.5.2 -- Enthought, Inc. (x86_64)
```

When I run the zotero command example `zot impact` ( I have pdf with title impact of something in zotero), it fails and gives following debug message:

```
Starting debug for 'ZotHero'

[2018-09-07 11:01:49][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "./zh", line 49, in <module>
    from workflow import Workflow3, ICON_WARNING, ICON_WEB
  File "./lib/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "./lib/workflow/workflow.py", line 25, in <module>
    import cPickle
ImportError: No module named 'cPickle'
[2018-09-07 11:01:49][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "./zh", line 49, in <module>
    from workflow import Workflow3, ICON_WARNING, ICON_WEB
  File "./lib/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "./lib/workflow/workflow.py", line 25, in <module>
    import cPickle
ImportError: No module named 'cPickle'
[2018-09-07 11:01:50][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "./zh", line 49, in <module>
    from workflow import Workflow3, ICON_WARNING, ICON_WEB
  File "./lib/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "./lib/workflow/workflow.py", line 25, in <module>
    import cPickle
ImportError: No module named 'cPickle'
[2018-09-07 11:01:50][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "./zh", line 49, in <module>
    from workflow import Workflow3, ICON_WARNING, ICON_WEB
  File "./lib/workflow/__init__.py", line 16, in <module>
    from .workflow import Workflow, manager
  File "./lib/workflow/workflow.py", line 25, in <module>
    import cPickle
ImportError: No module named 'cPickle'
```

Note that this workflow runs fine in my laptop with pyton2.7 but it fails in office computer with aliased python.

I can not alias python2 to python in office computer.

Is there a way to circumvent this problem?

**Comment by deanishe** [comment]
> Is there a way to circumvent this problem?

The obvious answer is to get your machine unfucked. `/usr/bin/python` is part of macOS. Replacing it with something else is a bad idea. Replacing it with an incompatible version is insane. Your own crap belongs in `/usr/local/bin` or `~/bin`.

Failing that, you'll need to install a compatible version of Python 2.7 plus PyObjC (not part of Python, but installed by default in the macOS system Python), and then edit the workflow's source code and change any reference to `/usr/bin/python` (there are several) to point to your new 2.7 installation.

And you'll have to repeat that for other Python workflows, as very many hardcode `/usr/bin/python` precisely to avoid being run with an incompatible, non-system version of Python.
