### ISSUE TITLE
copying Better BibTex citekey

### ISSUE THREAD

**Issue by mgass** [deanishe/zothero#44]
While attempting to copy a Better BibTex citekey an error is raised. I have set COPY_CITEKEY_MOD differently (fn, cmd, ctrl) to check, but find the same result.

This is the error from the log:

```13:11:27 util.py:273 INFO     [0.02s] load Better Bibtex data
13:11:27 workflow.py:2080 ERROR    'NoneType' object has no attribute 'tags'
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./zh", line 714, in main
    return do_reindex()
  File "./zh", line 597, in do_reindex
    app.update_index(force=False)
  File "./lib/zothero/core.py", line 166, in update_index
    self.index.update(self.zotero, force)
  File "./lib/zothero/index.py", line 277, in update
    if not self._update(zot, force):
  File "./lib/zothero/index.py", line 327, in _update
    tags = u' '.join(e.tags)
```

The Alfred window shows "Open in Zotero" when using the chosen key.

**Comment by mgass** [comment]
never mind. 😁 All seems to be working after hitting Reload Zotero Data.

Suggestion: if reloading is necessary after modifying COPY_CITEKEY_MOD, it may be helpful to add that step in the documentation.

Thank you for Zothero!

**Comment by deanishe** [comment]
> if reloading is necessary after modifying COPY_CITEKEY_MOD

It isn't. The Better BibTex feature wasn't implemented properly, so it's likely that automatic reloading had failed.

**Comment by stighagen** [comment]
Hi :-) I got the Better Bibtex key working, but it shows only e.g:
barton2012
Is it possible to make it markdown ready like this:
[@barton2012]

**Comment by zzzgithubzzz** [comment]
Hi, am a novice in this. Could you please elaborate on how to use COPY_CITEKEY_MOD to copy BibTex citekey from the workflow? A step-by-step guide of sorts ? 🙏  Thank you

**Comment by kenanmike** [comment]
Hi @deanishe I have the same question as @zzzgithubzzz - I don't understand where to find the COPY_CITEKEY_MOD on the workflow configuration page or how to set it to output by default on hitting return/enter (I only need fn + return/enter to open Zotero).

**Comment by kenanmike** [comment]
Actually I just worked out how to do it. 
@zzzgithubzzz click the x in the top right corner of the workflow like this:
![image](https://user-images.githubusercontent.com/85374001/131798124-e4e35274-30a7-46f3-a7ec-d7ca3fe418f4.png)
Then just click the 'value' of COPY_CITEKEY_MOD and put '-' to work on enter, or just hit the key on the keyboard you want to use (say, Fn key).
![image](https://user-images.githubusercontent.com/85374001/131798265-bd8365d6-0986-42d9-ba1a-bffff3d6db94.png)

**Comment by zzzgithubzzz** [comment]
Hi, 
Thank you @kenanmike for the reply. Just hitting the Fn key did not enable it. However, I typed in ‘fn’ in the COPY_CITEKEY_MOD value. Now, I am able to directly copy the citekey albeit without the ‘@‘ prefix.
Cheers 😊

**Comment by stighagen** [comment]
I would love to include brackets and @, e.g: [@barton2012]

If any comes across a solution, please share :-)

**Comment by kenanmike** [comment]
Yes, I’d recommend checking out the ‘Pandoc suite’ Alfred workflow which enters the citation pickers with @ and [ brackets by default. Get it here:
https://chris-grieser.de/pandoc_alfred
I use both that and this workflow for different purposes

**Comment by stighagen** [comment]
@kenanmike Thank you! Just downloaded it, and works exactly like I want it too :-)
