### ISSUE TITLE
failing to update in ARM environment

### ISSUE THREAD

**Issue by FuZhiyu** [deanishe/zothero#47]
I'm on an M1 mac mini, with the universal build of Alfred. This workflow doesn't work due to update failure. See below for the log:

```

15:47:18 workflow.py:2338 INFO     checking for update ...
15:47:18 update.py:472 INFO     14 download(s) for deanishe/zothero
15:47:18 update.py:564 ERROR    suffix must start with - :  Universal
Traceback (most recent call last):
  File "./lib/workflow/update.py", line 557, in <module>
    check_update(repo, version, prereleases)
  File "./lib/workflow/update.py", line 474, in check_update
    dl = latest_download(dls, alfred_version, prereleases)
  File "./lib/workflow/update.py", line 420, in latest_download
    version = Version(alfred_version)
  File "./lib/workflow/update.py", line 242, in __init__
    self._parse(vstr)
  File "./lib/workflow/update.py", line 271, in _parse
    'suffix must start with - : ' + suffix)
ValueError: suffix must start with - :  Universal
15:47:18 background.py:285 ERROR    [__workflow_update_check] command failed with status 1
15:47:22 workflow.py:2338 INFO     checking for update ...
15:47:22 update.py:472 INFO     14 download(s) for deanishe/zothero
15:47:22 update.py:564 ERROR    suffix must start with - :  Universal
Traceback (most recent call last):
  File "./lib/workflow/update.py", line 557, in <module>
    check_update(repo, version, prereleases)
  File "./lib/workflow/update.py", line 474, in check_update
    dl = latest_download(dls, alfred_version, prereleases)
  File "./lib/workflow/update.py", line 420, in latest_download
    version = Version(alfred_version)
  File "./lib/workflow/update.py", line 242, in __init__
    self._parse(vstr)
  File "./lib/workflow/update.py", line 271, in _parse
    'suffix must start with - : ' + suffix)
ValueError: suffix must start with - :  Universal
15:47:22 background.py:285 ERROR    [__workflow_update_check] command failed with status 1
15:47:22 workflow.py:2338 INFO     checking for update ...
15:47:22 workflow.py:2338 INFO     checking for update ...
15:47:23 background.py:260 CRITICAL [__workflow_update_check] command cache not found: /Users/zhiyufu/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero/__workflow_update_check.argcache
15:47:23 workflow.py:2080 ERROR    [__workflow_update_check] command cache not found: /Users/zhiyufu/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero/__workflow_update_check.argcache
Traceback (most recent call last):
  File "/Users/zhiyufu/Dropbox/Alfred.alfredpreferences/workflows/user.workflow.A1B7B70F-F554-4AC7-85C9-0EAFB074FD20/lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./lib/workflow/background.py", line 261, in main
    raise IOError(msg)
IOError: [__workflow_update_check] command cache not found: /Users/zhiyufu/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero/__workflow_update_check.argcache
15:47:23 update.py:472 INFO     14 download(s) for deanishe/zothero
15:47:23 update.py:564 ERROR    suffix must start with - :  Universal
Traceback (most recent call last):
  File "./lib/workflow/update.py", line 557, in <module>
    check_update(repo, version, prereleases)
  File "./lib/workflow/update.py", line 474, in check_update
    dl = latest_download(dls, alfred_version, prereleases)
  File "./lib/workflow/update.py", line 420, in latest_download
    version = Version(alfred_version)
  File "./lib/workflow/update.py", line 242, in __init__
    self._parse(vstr)
  File "./lib/workflow/update.py", line 271, in _parse
    'suffix must start with - : ' + suffix)
ValueError: suffix must start with - :  Universal
```

**Comment by masteranza** [comment]
@FuZhiyu I'm guessing this might have been due to Alfred. Update Alfred and check if it's still not working.

**Comment by FuZhiyu** [comment]
@masteranza Sorry for the late update. It has been solved indeed. You can close this issue now. Thanks!
