### ISSUE TITLE
Cannot copy to clipboard on MacOS catalina

### ISSUE THREAD

**Issue by eppfel** [deanishe/zothero#57]
When I try to copy bibliography using the `alt`key nothing happens. The debug shows and  "permission denied" error.  I'm on Mac, so I thought that could be caused by the OS. However, Alfred has all necessary permissions. 

I don't remember if it has ever worked on this machine, because I only have it for about two months.

BTW, awesome project. Where can I buy you a coffee?

<details>

```

[12:31:21.514] ZotHero[Script Filter] Processing complete
[12:31:21.515] ZotHero[Script Filter] Passing output '1403' to Debug
[12:31:21.516] ZotHero[Debug] .
/----------- ZOT OUT -----------\
query=1403
variables={
  action = "copy-citation"
  ATTACHMENTS_DIR = ""
  bibliography = "1"
  CITE_STYLE = "http://www.zotero.org/styles/association-for-computing-machinery"
  citekey = "koelleWhatAcceptableThoughts2019"
  COPY_CITEKEY_MOD = ""
  id = "1403"
  LOCALE = "en-GB"
  style = "http://www.zotero.org/styles/association-for-computing-machinery"
  stylename = "Association for Computing Machinery"
  url = "zotero://select/items/1_W655LZEA"
  ZOTERO_DIR = ""
}
\-------------------------------/
[12:31:21.518] ZotHero[Debug] Processing complete
[12:31:21.519] ZotHero[Debug] Passing output '1403' to Filter
[12:31:21.521] ZotHero[Debug] Passing output '1403' to Filter
[12:31:21.522] ZotHero[Debug] Passing output '1403' to Filter
[12:31:21.523] ZotHero[Debug] Passing output '1403' to Filter
[12:31:21.524] ZotHero[Debug] Passing output '1403' to Filter
[12:31:21.525] ZotHero[Filter] Processing complete
[12:31:21.526] ZotHero[Filter] Passing output '1403' to Call External Trigger
[12:31:21.527] ZotHero[External] Processing complete
[12:31:21.528] ZotHero[External] Passing output '' to Filter
[12:31:21.529] ZotHero[Filter] Processing complete
[12:31:21.530] ZotHero[Filter] Passing output '' to Script Filter
[12:31:21.538] ZotHero[External] Passing output '' to Debug
[12:31:21.540] ZotHero[Debug] .
/------- COPY CITATION IN --------\
query=
variables={
  action = "copy-citation"
  ATTACHMENTS_DIR = ""
  bibliography = "1"
  CITE_STYLE = "http://www.zotero.org/styles/association-for-computing-machinery"
  citekey = "koelleWhatAcceptableThoughts2019"
  COPY_CITEKEY_MOD = ""
  id = "1403"
  LOCALE = "en-GB"
  style = "http://www.zotero.org/styles/association-for-computing-machinery"
  stylename = "Association for Computing Machinery"
  url = "zotero://select/items/1_W655LZEA"
  ZOTERO_DIR = ""
}
\---------------------------------/
[12:31:21.543] ZotHero[Debug] Processing complete
[12:31:21.544] ZotHero[Debug] Passing output '' to Hide Alfred
[12:31:21.556] ZotHero[Hide Alfred] Processing complete
[12:31:21.558] ZotHero[Hide Alfred] Passing output '' to Run Script
[12:31:21.560] ZotHero[Script Filter] Queuing argument ''
[12:31:21.632] ZotHero[Script Filter] Script with argv '' finished
[12:31:21.641] ZotHero[Script Filter] {
	"items": [
		{
			"title": "Generating Citation…",
			"subtitle": "This window will disappear when your citation is on the pasteboard",
			"icon": {
				"path": "icons/reload.png"
			},
			"valid": false
		}
	]
}
```

</details>

```

[12:31:22.136] STDERR: ZotHero[Run Script] .
12:31:21 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
12:31:21 workflow.py:1468 DEBUG    reading settings from /Users/eppf1/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
12:31:21 workflow.py:2343 DEBUG    update check not due
12:31:21 zh:667 DEBUG    args={'--bibliography': True,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': u'1403',
 '<key>': None,
 '<query>': None,
 '<style>': u'http://www.zotero.org/styles/association-for-computing-machinery',
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': True,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': False}
12:31:21 config.py:88 DEBUG    [config] attachdir=u'/Users/eppf1/OneDrive - Aalto University/PhD/ZoteroFiles'
12:31:21 config.py:85 DEBUG    [config] datadir=u'/Users/eppf1/Zotero'
12:31:21 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
12:31:21 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
12:31:21 core.py:74 DEBUG    [core] attachments_dir=u'~/OneDrive - Aalto University/PhD/ZoteroFiles'
12:31:22 index.py:153 DEBUG    [index] opened u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero/search.sqlite'
12:31:22 core.py:133 DEBUG    [core] storage=u'~/Zotero/storage'
12:31:22 core.py:134 DEBUG    [core] styles=u'~/Zotero/styles'
12:31:22 cache.py:311 DEBUG    [cache] opening store 'styles'...
12:31:22 cache.py:311 DEBUG    [cache] opening store 'modtimes'...
12:31:22 styles.py:219 DEBUG    [styles] locale=u'en-GB'
12:31:22 styles.py:220 DEBUG    [styles] style=CSLStyle(name=u'Association for Computing Machinery', path=u'/Users/eppf1/Zotero/styles/association-for-computing-machinery.csl')
12:31:22 styles.py:221 DEBUG    [styles] csl={u'volume': u'26', u'DOI': u'10.1145/3319073', u'shortTitle': u'What is (un)acceptable?', u'language': u'en', u'author': [{'given': u'Marion', 'family': u'Koelle'}, {'given': u'Thomas', 'family': u'Olsson'}, {'given': u'Robb', 'family': u'Mitchell'}, {'given': u'Julie', 'family': u'Williamson'}, {'given': u'Susanne', 'family': u'Boll'}], u'URL': u'http://dl.acm.org/citation.cfm?doid=3328418.3319073', u'issued': {'date-parts': [[2019, 4, 23]]}, u'title': u'What is (un)acceptable?: thoughts on social acceptability in HCI research', u'page': u'36-40', u'ISSN': u'10725520', u'source': u'DOI.org (Crossref)', u'issue': u'3', u'container-title': u'Interactions', u'accessed': {'date-parts': [[2019, 9, 5]]}, u'journalAbbreviation': u'Interactions', 'type': u'article-journal', 'id': u'W655LZEA'}
12:31:22 cite.py:47 DEBUG    [cite] cmd=['./lib/cite/cite', '--verbose', '--locale-dir', './lib/cite/locales', '--bibliography', '--locale', u'en-GB', u'/Users/eppf1/Zotero/styles/association-for-computing-machinery.csl', '/var/folders/4t/6w5qtn213kb75nh71b5kgv3m0000gn/T/tmpMYl9MJ.json']
12:31:22 workflow.py:2080 ERROR    [Errno 13] Permission denied
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./zh", line 702, in main
    args['--paste'])
  File "./zh", line 352, in do_copy
    data = app.styles.cite(e, s, bib_style, LOCALE)
  File "./lib/zothero/styles.py", line 224, in cite
    return cite.generate(entry.csl, style.path, bibliography, locale)
  File "./lib/cite/cite.py", line 50, in generate
    stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
12:31:22 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/zothero/issues
12:31:22 workflow.py:2103 DEBUG    ---------- finished in 0.396s ----------

```

**Comment by KwanWaiChung** [comment]
Hi, unrelated to your problem but I saw you have successfully set your citation style. I wonder how you did it because as stated in #59 I can't set the style. Thanks
