### ISSUE TITLE
Can't update any settings

### ISSUE THREAD

**Issue by KwanWaiChung** [deanishe/zothero#59]
Below is the debugger output when I tried to config the citation style. Nothing happens after I clicked enter. Same goes for other settings. Below is the debugger output. I am using alfred 4.0.9. It seems to be similar to #22 but you said you have updated for alfred 4 already so I don't know what's going on.  

[10:39:02.668] Logging Started...
[10:39:17.123] ZotHero[Script Filter] Queuing argument ''
[10:39:17.307] ZotHero[Script Filter] Script with argv '' finished
[10:39:17.311] STDERR: ZotHero[Script Filter] .
10:39:17 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
10:39:17 workflow.py:1468 DEBUG    reading settings from /Users/student-t/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
10:39:17 workflow.py:2343 DEBUG    update check not due
10:39:17 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': u'',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': True,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': False}
10:39:17 config.py:88 DEBUG    [config] attachdir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:17 config.py:85 DEBUG    [config] datadir=u'/Users/student-t/Zotero'
10:39:17 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
10:39:17 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
10:39:17 core.py:74 DEBUG    [core] attachments_dir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:17 workflow.py:1695 DEBUG    loading cached data: /Users/student-t/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero/__workflow_latest_version.cpickle
10:39:17 workflow.py:2254 DEBUG    set last run version: 1.3.0
10:39:17 workflow.py:2103 DEBUG    ---------- finished in 0.030s ----------
[10:39:17.314] ZotHero[Script Filter] {"items": [{"autocomplete": "workflow:update", "valid": false, "subtitle": "\u21a9 or \u21e5 to force update check", "icon": {"path": "icons/update-ok.png"}, "title": "Workflow is Up To Date"}, {"variables": {"action": "choose-style", "varname": "CITE_STYLE", "style": ""}, "valid": true, "subtitle": "\u21a9 to change style", "icon": {"path": "icons/off.png"}, "title": "Default Style: None"}, {"variables": {"action": "choose-locale", "varname": "LOCALE"}, "valid": true, "subtitle": "\u21a9 to change locale", "icon": {"path": "icons/locale.png"}, "title": "Locale: Default (US English)"}, {"variables": {"action": "reload"}, "valid": true, "subtitle": "Re-read your Zotero database", "icon": {"path": "icons/reload.png"}, "title": "Reload Zotero Data"}, {"autocomplete": "workflow:openlog", "valid": false, "subtitle": "Open workflow log file in default app", "icon": {"path": "icons/log.png"}, "title": "Open Log File"}, {"subtitle": "Open the documentation in your browser", "title": "View Documentation", "variables": {"url": "https://github.com/deanishe/zothero/blob/master/README.md", "action": "open-url"}, "valid": true, "arg": "https://github.com/deanishe/zothero/blob/master/README.md", "icon": {"path": "icons/docs.png"}}, {"subtitle": "Open GitHub issue tracker in your browser", "title": "Report an Issue", "variables": {"url": "https://github.com/deanishe/zothero/issues", "action": "open-url"}, "valid": true, "arg": "https://github.com/deanishe/zothero/issues", "icon": {"path": "icons/issue.png"}}]}
[10:39:21.315] ZotHero[Script Filter] Processing complete
[10:39:21.316] ZotHero[Script Filter] Passing output '' to Debug
[10:39:21.335] ZotHero[Debug] .
/----------- CONF OUT -----------\
query=
variables={
  action = "choose-style"
  ATTACHMENTS_DIR = ""
  CITE_STYLE = ""
  COPY_CITEKEY_MOD = ""
  LOCALE = ""
  style = ""
  varname = "CITE_STYLE"
  ZOTERO_DIR = "~/Zotero"
}
\--------------------------------/
[10:39:21.336] ZotHero[Debug] Processing complete
[10:39:21.337] ZotHero[Debug] Passing output '' to Filter
[10:39:21.337] ZotHero[Filter] Processing complete
[10:39:21.338] ZotHero[Filter] Passing output '' to Script Filter
[10:39:21.338] ZotHero[Debug] Passing output '' to Filter
[10:39:21.339] ZotHero[Debug] Passing output '' to Filter
[10:39:21.339] ZotHero[Debug] Passing output '' to Filter
[10:39:21.340] ZotHero[Script Filter] Queuing argument ''
[10:39:21.424] ZotHero[Script Filter] Script with argv '' finished
[10:39:21.425] STDERR: ZotHero[Script Filter] .
10:39:21 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
10:39:21 workflow.py:1468 DEBUG    reading settings from /Users/student-t/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
10:39:21 workflow.py:2343 DEBUG    update check not due
10:39:21 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': u'',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': True}
10:39:21 config.py:88 DEBUG    [config] attachdir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:21 config.py:85 DEBUG    [config] datadir=u'/Users/student-t/Zotero'
10:39:21 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
10:39:21 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
10:39:21 core.py:74 DEBUG    [core] attachments_dir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:21 core.py:133 DEBUG    [core] storage=u'~/Zotero/storage'
10:39:21 core.py:134 DEBUG    [core] styles=u'~/Zotero/styles'
10:39:21 cache.py:311 DEBUG    [cache] opening store 'styles'...
10:39:21 cache.py:311 DEBUG    [cache] opening store 'modtimes'...
10:39:21 workflow.py:2254 DEBUG    set last run version: 1.3.0
10:39:21 workflow.py:2103 DEBUG    ---------- finished in 0.049s ----------
[10:39:21.430] ZotHero[Script Filter] {"items": [{"variables": {"varval": "http://www.zotero.org/styles/american-chemical-society", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "American Chemical Society"}, {"variables": {"varval": "http://www.zotero.org/styles/american-medical-association", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "American Medical Association 11th edition"}, {"variables": {"varval": "http://www.zotero.org/styles/american-political-science-association", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "American Political Science Association"}, {"variables": {"varval": "http://www.zotero.org/styles/american-sociological-association", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "American Sociological Association 6th edition"}, {"variables": {"varval": "http://www.zotero.org/styles/apa", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "American Psychological Association 7th edition"}, {"variables": {"varval": "http://www.zotero.org/styles/chicago-author-date", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Chicago Manual of Style 17th edition (author-date)"}, {"variables": {"varval": "http://www.zotero.org/styles/chicago-fullnote-bibliography", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Chicago Manual of Style 17th edition (full note)"}, {"variables": {"varval": "http://www.zotero.org/styles/chicago-note-bibliography", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Chicago Manual of Style 17th edition (note)"}, {"variables": {"varval": "http://www.zotero.org/styles/elsevier-harvard", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Elsevier - Harvard (with titles)"}, {"variables": {"varval": "http://www.zotero.org/styles/harvard-cite-them-right", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Cite Them Right 10th edition - Harvard"}, {"variables": {"varval": "http://www.zotero.org/styles/ieee", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "IEEE"}, {"variables": {"varval": "http://www.zotero.org/styles/modern-humanities-research-association", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Modern Humanities Research Association 3rd edition (note with bibliography)"}, {"variables": {"varval": "http://www.zotero.org/styles/modern-language-association", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Modern Language Association 8th edition"}, {"variables": {"varval": "http://www.zotero.org/styles/nature", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Nature"}, {"variables": {"varval": "http://www.zotero.org/styles/vancouver", "next": "config"}, "valid": true, "subtitle": "\u21a9 to set as default style", "icon": {"path": "icons/off.png"}, "title": "Vancouver"}]}
[10:39:24.107] ZotHero[Script Filter] Processing complete
[10:39:24.119] ZotHero[Script Filter] Passing output '' to Call External Trigger
[10:39:24.120] ZotHero[External] Processing complete
[10:39:24.120] ZotHero[External] Passing output '' to Debug
[10:39:24.121] ZotHero[Debug] .
/----------- SETVAR IN -----------\
query=
variables={
  action = "choose-style"
  ATTACHMENTS_DIR = ""
  CITE_STYLE = ""
  COPY_CITEKEY_MOD = ""
  LOCALE = ""
  next = "config"
  style = ""
  varname = "CITE_STYLE"
  varval = "http://www.zotero.org/styles/ieee"
  ZOTERO_DIR = "~/Zotero"
}
\---------------------------------/
[10:39:24.122] ZotHero[Debug] Processing complete
[10:39:24.123] ZotHero[Debug] Passing output '' to Run Script
[10:39:24.397] STDERR: ZotHero[Run Script] .
10:39:24 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
10:39:24 workflow.py:1468 DEBUG    reading settings from /Users/student-t/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
10:39:24 workflow.py:2343 DEBUG    update check not due
10:39:24 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': u'CITE_STYLE',
 '<query>': None,
 '<style>': None,
 '<value>': u'http://www.zotero.org/styles/ieee',
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': True,
 'style': False}
10:39:24 config.py:88 DEBUG    [config] attachdir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:24 config.py:85 DEBUG    [config] datadir=u'/Users/student-t/Zotero'
10:39:24 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
10:39:24 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
10:39:24 core.py:74 DEBUG    [core] attachments_dir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:24 zh:609 DEBUG    [settings] setting "CITE_STYLE" to "http://www.zotero.org/styles/ieee" ...
execution error: Error: Error: An error occurred. (-1743)
10:39:24 workflow.py:2080 ERROR    Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', 'Application("com.runningwithcrayons.Alfred").setConfiguration("CITE_STYLE", {"exportable": true, "inWorkflow": "net.deanishe.alfred.zothero", "toValue": "http://www.zotero.org/styles/ieee"});']' returned non-zero exit status 1
Traceback (most recent call last):
  File "./lib/workflow/workflow.py", line 2073, in run
    func(self)
  File "./zh", line 723, in main
    return do_setvar(args['<key>'], args['<value>'])
  File "./zh", line 610, in do_setvar
    set_config(key, value, exportable=True)
  File "./lib/workflow/util.py", line 292, in set_config
    run_applescript(script, lang='JavaScript')
  File "./lib/workflow/util.py", line 219, in run_applescript
    return run_command(cmd, **kwargs)
  File "./lib/workflow/util.py", line 184, in run_command
    return subprocess.check_output(cmd, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', 'Application("com.runningwithcrayons.Alfred").setConfiguration("CITE_STYLE", {"exportable": true, "inWorkflow": "net.deanishe.alfred.zothero", "toValue": "http://www.zotero.org/styles/ieee"});']' returned non-zero exit status 1
10:39:24 workflow.py:2082 INFO     for assistance, see: https://github.com/deanishe/zothero/issues
10:39:24 workflow.py:2103 DEBUG    ---------- finished in 0.117s ----------
[10:39:24.400] ZotHero[Run Script] Processing complete
[10:39:24.401] ZotHero[Run Script] Passing output '{"items": [{"valid": false, "subtitle": "Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', 'Application(\"com.runningwithcrayons.Alfred\").setConfiguration(\"CITE_STYLE\", {\"exportable\": true, \"inWorkflow\": \"net.deanishe.alfred.zothero\", \"toValue\": \"http://www.zotero.org/styles/ieee\"});']' returned non-zero exit status 1", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'ZotHero'"}]}' to Call External Trigger
[10:39:24.402] ZotHero[External] Processing complete
[10:39:24.402] ZotHero[External] Passing output '' to Run Script
[10:39:24.403] ZotHero[Run Script] Passing output '{"items": [{"valid": false, "subtitle": "Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', 'Application(\"com.runningwithcrayons.Alfred\").setConfiguration(\"CITE_STYLE\", {\"exportable\": true, \"inWorkflow\": \"net.deanishe.alfred.zothero\", \"toValue\": \"http://www.zotero.org/styles/ieee\"});']' returned non-zero exit status 1", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'ZotHero'"}]}' to Filter
[10:39:24.404] ZotHero[Filter] Processing complete
[10:39:24.404] ZotHero[Filter] Passing output '{"items": [{"valid": false, "subtitle": "Command '['/usr/bin/osascript', '-l', 'JavaScript', '-e', 'Application(\"com.runningwithcrayons.Alfred\").setConfiguration(\"CITE_STYLE\", {\"exportable\": true, \"inWorkflow\": \"net.deanishe.alfred.zothero\", \"toValue\": \"http://www.zotero.org/styles/ieee\"});']' returned non-zero exit status 1", "icon": {"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"}, "title": "Error in workflow 'ZotHero'"}]}' to Call External Trigger
[10:39:24.419] ZotHero[External] Processing complete
[10:39:24.420] ZotHero[External] Passing output '' to Script Filter
[10:39:24.421] ZotHero[Script Filter] Queuing argument ''
[10:39:24.556] STDERR: ZotHero[Run Script] .
10:39:24 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
10:39:24 workflow.py:1468 DEBUG    reading settings from /Users/student-t/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
10:39:24 workflow.py:2343 DEBUG    update check not due
10:39:24 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': None,
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': False,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': True,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': False}
10:39:24 config.py:88 DEBUG    [config] attachdir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:24 config.py:85 DEBUG    [config] datadir=u'/Users/student-t/Zotero'
10:39:24 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
10:39:24 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
10:39:24 core.py:74 DEBUG    [core] attachments_dir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:24 zh:627 DEBUG    ignoring empty notification
10:39:24 workflow.py:2254 DEBUG    set last run version: 1.3.0
10:39:24 workflow.py:2103 DEBUG    ---------- finished in 0.041s ----------
[10:39:24.585] ZotHero[Script Filter] Script with argv '' finished
[10:39:24.586] STDERR: ZotHero[Script Filter] .
10:39:24 workflow.py:2061 DEBUG    ---------- ZotHero (1.3.0) ----------
10:39:24 workflow.py:1468 DEBUG    reading settings from /Users/student-t/Library/Application Support/Alfred/Workflow Data/net.deanishe.alfred.zothero/settings.json
10:39:24 workflow.py:2343 DEBUG    update check not due
10:39:24 zh:667 DEBUG    args={'--bibliography': False,
 '--help': False,
 '--paste': False,
 '--style': None,
 '--text': None,
 '--title': None,
 '<citekey>': None,
 '<id>': None,
 '<key>': None,
 '<query>': u'',
 '<style>': None,
 '<value>': None,
 'attachments': False,
 'citations': False,
 'clear': False,
 'config': True,
 'copy': False,
 'fields': False,
 'locale': False,
 'notify': False,
 'reindex': False,
 'search': False,
 'setvar': False,
 'style': False}
10:39:24 config.py:88 DEBUG    [config] attachdir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:24 config.py:85 DEBUG    [config] datadir=u'/Users/student-t/Zotero'
10:39:24 core.py:72 DEBUG    [core] cachedir=u'~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero'
10:39:24 core.py:73 DEBUG    [core] zotero_dir=u'~/Zotero'
10:39:24 core.py:74 DEBUG    [core] attachments_dir=u'/Volumes/My Passport/Data/GoogleDrive/paper'
10:39:24 workflow.py:1695 DEBUG    loading cached data: /Users/student-t/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/net.deanishe.alfred.zothero/__workflow_latest_version.cpickle
10:39:24 workflow.py:2254 DEBUG    set last run version: 1.3.0
10:39:24 workflow.py:2103 DEBUG    ---------- finished in 0.033s ----------
[10:39:24.588] ZotHero[Script Filter] {"items": [{"autocomplete": "workflow:update", "valid": false, "subtitle": "\u21a9 or \u21e5 to force update check", "icon": {"path": "icons/update-ok.png"}, "title": "Workflow is Up To Date"}, {"variables": {"action": "choose-style", "varname": "CITE_STYLE", "style": ""}, "valid": true, "subtitle": "\u21a9 to change style", "icon": {"path": "icons/off.png"}, "title": "Default Style: None"}, {"variables": {"action": "choose-locale", "varname": "LOCALE"}, "valid": true, "subtitle": "\u21a9 to change locale", "icon": {"path": "icons/locale.png"}, "title": "Locale: Default (US English)"}, {"variables": {"action": "reload"}, "valid": true, "subtitle": "Re-read your Zotero database", "icon": {"path": "icons/reload.png"}, "title": "Reload Zotero Data"}, {"autocomplete": "workflow:openlog", "valid": false, "subtitle": "Open workflow log file in default app", "icon": {"path": "icons/log.png"}, "title": "Open Log File"}, {"subtitle": "Open the documentation in your browser", "title": "View Documentation", "variables": {"url": "https://github.com/deanishe/zothero/blob/master/README.md", "action": "open-url"}, "valid": true, "arg": "https://github.com/deanishe/zothero/blob/master/README.md", "icon": {"path": "icons/docs.png"}}, {"subtitle": "Open GitHub issue tracker in your browser", "title": "Report an Issue", "variables": {"url": "https://github.com/deanishe/zothero/issues", "action": "open-url"}, "valid": true, "arg": "https://github.com/deanishe/zothero/issues", "icon": {"path": "icons/issue.png"}}]}

**Comment by eppfel** [comment]
Same error here. Can't change the citation style anymore.
